fluidPage(
  shinyjs::useShinyjs(),
  
  titlePanel("Mental Health Population Estimation"),

  sidebarLayout(
    # Side Bar Panel
    sidebarPanel(
      selectInput(inputId = 'edtPopnRegion',
                  label = 'Popn Region',
                  choices = setNames(c('ALL', df_popn_hierarchy %>% dplyr::filter(parent_org_id == 'ENG') %>% .$org_id), 
                                     c('ALL', df_popn_hierarchy %>% dplyr::filter(parent_org_id == 'ENG') %>% .$org_name)),
                  selected = 'ALL'),
      selectInput(inputId = 'edtPopnICB',
                  label = 'Popn ICB',
                  choices = 'None'),
      selectInput(inputId = 'edtPopnSubICB',
                  label = 'Popn Sub-ICB',
                  choices = 'None'),
      selectInput(inputId = 'edtPopnPCN',
                  label = 'Popn PCN',
                  choices = 'None'),
      selectInput(inputId = 'edtPopnPrac',
                  label = 'Popn Practice',
                  choices = 'None'),
      # selectInput(inputId = 'edtAgeBand',
      #             label = 'Age Bands',
      #             selected = 'All',
      #             choices = c('00-04','05-09',
      #                         '10-14','15-19',
      #                         '20-24','25-29',
      #                         '30-34','35-39',
      #                         '40-44','45-49',
      #                         '50-54','55-59',
      #                         '60-64','65-69',
      #                         '70-74','75-79',
      #                         '80-84','85-89',
      #                         '90-94','95+'),
      #             multiple = TRUE),
      selectInput(inputId = 'edtPrevRegion',
                  label = 'Prevalence|Incidence Region',
                  choices = setNames(c('ALL', df_gbd_locations %>% dplyr::filter(parent_id == 4749) %>% .$loc_id), 
                                     c('ALL', df_gbd_locations %>% dplyr::filter(parent_id == 4749) %>% .$loc_name))),
      selectInput(inputId = 'edtPrevUTLA',
                  label = 'Prevalence|Incidence UTLA',
                  choices = 'None'),
      checkboxGroupInput(inputId = 'chkPrevIncd',
                         label = 'Prevalence|Incidence',
                         choices = c('Prevalence', 'Incidence'),
                         selected = 'Prevalence'),
      selectInput(inputId = 'edtCauses',
                  label = 'Causes',
                  choices = setNames(df_gbd_causes %>% dplyr::filter(parent_id %in% c(558, 567, 572, 973, 561)) %>% .$cause_id, 
                                     df_gbd_causes %>% dplyr::filter(parent_id %in% c(558, 567, 572, 973, 561)) %>% .$cause_name),
                  multiple = TRUE)
    ),
    # Main Panel
    mainPanel()
  )
)